# Basic variables for the Azure hosts
app_port: 8080
branch: "main"
db_ip: "4.223.107.0"
user: "{{ansible_user_id}}"
group: "{{ansible_user_gid}}"


app_dir: "{{ ansible_user_dir }}/ds-project-2024"

mailhog_path: "{{ ansible_user_dir }}/bin"
mailhog_version: v1.0.1
mailhog_ui_port: 8025
smtp_port: 1025

minio_download_dir: /tmp/minio.deb
minio_dir: "{{ ansible_user_dir }}/minio"
minio_api_port: 9000
minio_console_port: 9001

app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: myuser
    spring.datasource.password: pass12345
    spring.datasource.url: "jdbc:mariadb://{{ db_ip }}:3306/mariadb"
    spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect

    spring.mail.host: "{{ public_ip }}"
    spring.mail.port: "{{ smtp_port }}"
    spring.mail.username: noreply.springboot21@gmail.com
    spring.mail.password: no-password-needed
    spring.mail.properties.mail.smtp.auth: false
    spring.mail.properties.mail.smtp.starttls.enable: false

    minio.url: "http://{{ public_ip }}:{{ minio_api_port }}"
    minio.access.name: Q3AM3UQ867SPQQA43P2F
    minio.access.secret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    minio.bucket.name: pet-adoption-app
    minio.bucket.path: "https://{{ server_name }}/${minio.bucket.name}"

service:
  app:
    workingdir: "{{ ansible_user_dir }}/ds-project-2024"
    execstart: "java -jar {{ ansible_user_dir }}/ds-project-2024/target/ds-project-2024-0.0.1-SNAPSHOT.jar"
  mailhog:
    workingdir: "{{ mailhog_path }}"
    execstart: "{{ mailhog_path }}/MailHog"
  minio:
    execstart: '/usr/local/bin/minio server {{ minio_dir }} --console-address ":9001"'
    username: Q3AM3UQ867SPQQA43P2F
    password: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG