---
  - name: Setup Jenkins environment and remote VM access
    hosts: devops-vm-1

    tasks:

      - name: Install Ansible, Docker
        apt:
          name: {{item}}
          state: present
          update_cache: yes
        loop:
          - ansible-core
          - docker.io

      - name: Start ssh-agent and add Jenkins SSH key
        become: yes
        become_user: jenkins
        shell: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        environment:
          SSH_ASKPASS: /bin/true  # avoid interactive prompts
          DISPLAY: :0             # needed in some cases for SSH_ASKPASS to work
        register: ssh_agent_result

      