---
azure-hosts:
  hosts:
    devops-vm-1:
      ansible_host: az-devops
    devops-vm-2:
      ansible_host: service-vm

db-servers:
  hosts:
    db-server:
      ansible_host: db-vm

# Had some difficulties with the local-vms group, using vagrant, so I commented it out and i use only azure vms
# local-vms:
#   hosts:
#     local-vm-1:
#       ansible_host: local-db