---
azure-hosts:
  hosts:
    devops-vm-1:
      ansible_host: jenkins-vm # Mostly used for Jenkins, but can be used for other tasks as well
    devops-vm-2:
      ansible_host: ansible-vm # Mostly used for Ansible tasks, but can be used for other tasks as well
    devops-vm-3:
      ansible_host: docker-vm # !!!!Only used for Docker tasks!!!!

db-servers:
  hosts:
    db-server:
      ansible_host: db-vm

# Had some difficulties with the local-vms group, using vagrant, so I commented it out and i use only azure vms
# local-vms:
#   hosts:
#     local-vm-1:
#       ansible_host: local-db